---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
